### ISSUE TITLE
update action broke

### ISSUE THREAD

**Issue by chayleaf** [fufexan/nix-gaming#100]
https://github.com/fufexan/nix-gaming/actions/runs/5844403639/job/15847526297

```
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by fufexan** [comment]
I think reusable actions are run in separate clones. Shame.

**Comment by chayleaf** [comment]
i mean it's very logical, each job is done in isolation, you have to use steps of the same job  if you want to preserve some state from the previous steps

**Comment by fufexan** [comment]
Yes, I'll fix it today.

**Comment by fufexan** [comment]
@chayleaf has upstream changed existing releases for faf-client-unstable? I'm not sure why this action is failing https://github.com/fufexan/nix-gaming/actions/runs/5929910321/job/16078604726.

I've tried building it on my machine to make sure that GHA isn't at fault. I'm receiving a different error.
[faf-client-unstable.txt](https://github.com/fufexan/nix-gaming/files/12399618/faf-client-unstable.txt)

**Comment by chayleaf** [comment]
I'm thinking it could be due to a nixpkgs bump? Either that or it's some weird Gradle dependency issue, who knows. I'll add a `-f` flag for force updating the hashes.

**Comment by chayleaf** [comment]
Oh, this is probably the issue

```
Resource missing. [HTTP GET: https://jitpack.io/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7.pom]
Resource missing. [HTTP GET: https://maven.ej-technologies.com/repository/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7.pom]
```

I assume the locked dependencies got simply removed from the servers...

**Comment by fufexan** [comment]
Thanks for the fix!
