### ISSUE TITLE
Wine-ge questions

### ISSUE THREAD

**Issue by Henry-Hiles** [fufexan/nix-gaming#107]
It would be great if wine-ge could be updated, currently its `wine-8.0 (Staging)` which is quite old, thanks.

**Comment by fufexan** [comment]
`wine-ge` is on version `8.14`, as can be seen through `nix flake search github:fufexan/nix-gaming#wine-ge`. It might report the version as 8.0 when running `wine --version`, but it builds from the correct branch.

**Comment by Henry-Hiles** [comment]
Oh I see, thanks!

**Comment by Henry-Hiles** [comment]
One more question, why does wine-ge point to wine-proton and not https://github.com/GloriousEggroll/wine-ge-custom?

**Comment by fufexan** [comment]
The `wine-ge-custom` repository contains the build instructions to build a functional wine. You can see that `proton-wine` is pulled as a git submodule, and optionally combined with staging patches.

We do not need that functinoality, since we rely on the wine builder inside Nixpkgs.

**Comment by Henry-Hiles** [comment]
I see, thanks!
