### ISSUE TITLE
How to setup pipewire low latency with flakes

### ISSUE THREAD

**Issue by Henry-Hiles** [fufexan/nix-gaming#108]
Hello! I was wondering how i could enable pipewire low latency on flakes, thanks!

**Comment by fufexan** [comment]
First, make sure you have nix-gaming added as an input to your flake. Then, add the module like so:
```nix
# flake.nix
outputs = {self, nixpkgs, ...}@inputs: {
  nixosConfigurations.HOSTNAME = nixpkgs.lib.nixosSystem {
    modules = [
      # ...
      inputs.nix-gaming.nixosModules.pipewireLowLatency
    ];
  };
};
```
Alternatively, you can add `specialArgs = {inherit inputs;};` to the `nixosSystem` call, and you'll be able to use `inputs.nix-gaming.nixosModules.pipewireLowLatency` inside an `imports` list.

Finally, enable it as described in [this section](https://github.com/fufexan/nix-gaming#pipewire-low-latency).

**Comment by fufexan** [comment]
Thank you for the issue, I've updated the README. Hopefully it's clearer now.

**Comment by Henry-Hiles** [comment]
Much better, thanks! One more question, why couldn't these changes and packages be upstreamed?

**Comment by fufexan** [comment]
First of all, (most of) the games most likely don't allow redistribution/have an unfree license. Second of all, I havent't tried upstreaming, but if anyone's willing to upstream anything from here, they're more than welcome to.

**Comment by Henry-Hiles** [comment]
I see, thanks! Yeah I didn't mean the games, i meant more like the pipewire option, wine-ge and wine-tkg, and stuff like that

**Comment by fufexan** [comment]
Those could probably be upstreamed indeed.

**Comment by Henry-Hiles** [comment]
Yeah, if I were to do that, should I make the maintainer you, me, or both of us?

**Comment by fufexan** [comment]
You would be the maintainer, and you'd give me a notice so I can remove the package here and use the Nixpkgs one instead.

**Comment by Henry-Hiles** [comment]
I see, thanks. I might do that sometime then 👍
