### ISSUE TITLE
Update keeps rebuilding wine-ge-full-Proton8-26

### ISSUE THREAD

**Issue by kharf** [fufexan/nix-gaming#154]
After every update I get this warning:
`warning: ignoring substitute for '/nix/store/ls7c8562rwd56yy1dwcvg6bx0dywh04l-wine-ge-full-Proton8-26' from 'https://nix-gaming.cachix.org', as it's not signed by any of the keys in 'trusted-public-keys'`
and my system rebuilds this version.

The current proton version is 8-31 in the repository and the only reference to 8-26 I can see is here: https://github.com/fufexan/nix-gaming/blob/master/npins/sources.json#L108. I am not really sure what npins does in that case.
I checked the trusted key I configured here: https://github.com/kharf/nix-config/blob/main/nixos/configuration.nix#L41 and it seems to be the correct one still.
Is the pin maybe outdated and should pin the 8-31 branch or why do I get this warning?

**Comment by fufexan** [comment]
The problem is in your config. You wrote `unix-gaming` instead of `nix-gaming`.

**Comment by kharf** [comment]
> The problem is in your config. You wrote `unix-gaming` instead of `nix-gaming`.

how did i not see this. Sry, ty!
