### ISSUE TITLE
DXVK Broken (Upstream issue)

### ISSUE THREAD

**Issue by LovingMelody** [fufexan/nix-gaming#159]
DXVK is broken from upstream nixpkgs due to the transition to GCC 13 see (NixOS/nixpkgs#283642). We may want to consider pinning a nixpkgs version for DXVK or make changes to compile with GCC12. Looks like `github:NixOS/nixpkgs/b01852a162216ff5521c43254986fe3048a35f56` is the last working commit for nixos-unstable-small

**Comment by meenzen** [comment]
I think I'm running into this issue with Star Citizen, is there a workaround I can use until upstream is fixed?

**Comment by LovingMelody** [comment]
@meenzen You can use overlays and override the DXVK version. An example can be found in [nix-citizen](https://github.com/LovingMelody/nix-citizen/blob/bb3c68be1956bbaad813f3a16e2b9775510c1515/overlays.nix#L9)

**Comment by LovingMelody** [comment]
PR has been merged upstream not quite to nixpkgs-unstable
https://nixpk.gs/pr-tracker.html?pr=302187

**Comment by LovingMelody** [comment]
Issue can be closed w/ next flake update.

**Comment by LovingMelody** [comment]
Fixed by a8152ec
