### ISSUE TITLE
ProtonGE - Build from source

### ISSUE THREAD

**Issue by jh-devv** [fufexan/nix-gaming#168]
Hey!

Currently, it just uses the releases for it. Would probably be better to clone the release branch and just build from that.

You can find the build instructions here: https://github.com/GloriousEggroll/proton-ge-custom?tab=readme-ov-file#building

I can look into this!

**Comment by NotAShelf** [comment]
Why?

**Comment by jh-devv** [comment]
> Why?

The only reason would be adding custom WINE patches

**Comment by jh-devv** [comment]
Closing in favor of: https://github.com/NixOS/nixpkgs/pull/295785#issuecomment-1999531588
