### ISSUE TITLE
RLIMIT_NICE wineGE

### ISSUE THREAD

**Issue by juxuanu** [fufexan/nix-gaming#173]
Currently, the `wine` binary from WineGE shipped from this repo has no CAP_SYS_NICE set. This results in the following message logged when starting a random .exe file:

```
$ wine --boot

wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
``` 

This should be fixed applying the suggestion here: https://github.com/ValveSoftware/Proton/issues/6141#issuecomment-1563190512

Is this something actionable from this repository side? I'm guessing `setcap` should be used when packaging the final binary?

I'm sorry I am not creating a PR after testing it myself - I'm not familiar enough with NixOS yet.

**Comment by NotAShelf** [comment]
Derivations may not set their own capabilities - that has to be done by the host. You might want to take a look at [security.wrappers](https://search.nixos.org/options?channel=unstable&show=security.wrappers&from=0&size=50&sort=relevance&type=packages&query=security.wrappers) and wrap the WineGE package with your desired capabilities.

**Comment by juxuanu** [comment]
Thanks, I'll do that. Might be something useful to state on the docs, though!

**Comment by NotAShelf** [comment]
Honestly I didn't know wine-ge needed a cap wrapper, I don't use it. @fufexan what do you think, should we add a documentation entry on how to use wrappers or should the be a module for wine-ge?

**Comment by fufexan** [comment]
If we're providing docs, then the module is 2 steps away. I say we can provide that as well.
