### ISSUE TITLE
osu-stable won't install

### ISSUE THREAD

**Issue by atarashiryo** [fufexan/nix-gaming#174]
https://pastebin.com/iedDdjLN

**Comment by fufexan** [comment]
I'm not sure the problem is with kerberos, as there are many other errors that are not about it.

**Comment by atarashiryo** [comment]
yeah

**Comment by atarashiryo** [comment]
okay i can install it with bottles using this tut: https://osu.ppy.sh/community/forums/topics/1576494?n=1
but its technically still not fixed so im not gonna close this issue just yet

**Comment by Luk45135** [comment]
I think i have the same error. https://pastebin.com/YkE9aaZ3
Also the osu! updater opened and shows
Hi!
An error occurred! Please check your internet connection.

**Comment by atarashiryo** [comment]
thank god it wasn't just me that have this issue :moyai:

**Comment by atarashiryo** [comment]
just slightly :v
