### ISSUE TITLE
DXVK_HUD option for Rocket League

### ISSUE THREAD

**Issue by emrebicer** [fufexan/nix-gaming#178]
Is it possible to make the DXVK_HUD environment variable optional as well? I want to disable the `compiling shaders` text at the bottom left which keeps appearing throughout the gameplay. I believe I should set the environment variable DXVK_HUD to 0 to disable it, but it is currently hard coded in `writeShellScriptBin` at https://github.com/fufexan/nix-gaming/blob/a8c2a0e160e1212c67724aa89a823b55d423d157/pkgs/rocket-league/default.nix#L29

**Comment by fufexan** [comment]
Just pushed a commit that lets you override the derivation with `inputs.nix-gaming.packages.${pkgs.system}.rocket-league.override { dxvk_hud = "0"; }`. Hope this helps.

**Comment by emrebicer** [comment]
Thanks for the quick update. This was exactly what I was asking for, I just tested and it seems to work as expected, thanks!
