### ISSUE TITLE
star-citizen: Can't download game - launcher version 2.0.0 (beta)

### ISSUE THREAD

**Issue by Sntx626** [fufexan/nix-gaming#183]
When trying to install the game with the latest launcher, I get the following error:

![image](https://github.com/fufexan/nix-gaming/assets/48636286/da897173-de40-4542-8b7f-a462c237e684)

```log
21:00:08.440 > "[Installer] - Installing Star Citizen LIVE 3.23.1-live.9179031 at C:\\Program Files\\Roberts Space Industries\\StarCitizen"
21:00:08.447 > "[Installer] - Starting download of base pack (SC LIVE 3.23.1-live.9179031) in C:\\Program Files\\Roberts Space Industries\\StarCitizen"
21:00:08.449 > "[Initial-Download] - Initial download start"
01ac:fixme:explorerframe:taskbar_list_SetProgressState iface 0000000007642E30, hwnd 000000000001008E, flags 2 stub!
01ac:fixme:explorerframe:taskbar_list_SetProgressValue iface 0000000007642E30, hwnd 000000000001008E, ullCompleted 1, ullTotal 64 stub!
01ac:fixme:winsock:setsockopt Unknown IPPROTO_TCP optname 0x00000003
21:00:08.476 > "[InitialDownload Error] - verification download files failed: UnknownRemoteResourceError: Unknown error"
21:00:08.479 > "[Initial-Download] - Verification header not found for initial download"
21:00:08.480 > [
 "[Initial-download] - createInitialDownload error",
 {
  "error": {
   "name": "VerificationHeaderError"
  }
 }
]
21:00:08.482 > "[Installer] - Error installing at C:\\Program Files\\Roberts Space Industries\\StarCitizen\\LIVE: VerificationHeaderError: [Initial-Download] - Verification heade
r not found for initial download"
21:00:08.484 > [
 "[Installer] - Error: ",
 {
  "error": {
   "name": "VerificationHeaderError"
  }
 }
]
```

**Comment by damccull** [comment]
I was getting a similar error with the 2.0 launcher when trying to install it in proton earlier, but mine included an issue about being unable to create the installation folders because the user hadn't given permission. I assumed that was due to a broken UAC query or something. In this case I don't see it, but I wanted to throw my info here in case it was helpful. The legacy launcher seems to be doing well...

**Comment by fufexan** [comment]
@LovingMelody

**Comment by LovingMelody** [comment]
2.0 Launcher requires wine 9.5 or newer, wine-ge is a much older and does not have the patches back ported., If  you wish to use it anyways you will need to override the wine package and edit your host file to block the installation of EAC or use a patched version of wine that has the `EOS_USE_ANTICHEATCLIENTNULL` patch included

1.X launcher isnt going away any time soon and currently the 2.X launcher (which is in beta) only causes performance issues and wont really serve a purpose till SQ42 comes out..

**Comment by Sntx626** [comment]
Thanks for the response!

After your response I went back to the 1.X launcher and everything works.
I mistakingly thought that the 2.X launcher replaced the 1.X launcher.

In the future there'll probably be an issue on enabling the 2.X launcher,
but I'm closing this issue, since I see no reason to maintain the 2.X launcher for now.
