### ISSUE TITLE
Update request: osu-lazer-bin 2024.412.1 → 2024.519.1

### ISSUE THREAD

**Issue by Luk45135** [fufexan/nix-gaming#184]
- Package name: osu-lazer-bin
- Latest released version: 2024.519.1

- Current version on the nix-gaming channel: 2024.412.1
- I'm not quite sure what this 2024.517.0 version is as it's not a release upstream.

- [X ] Checked the [nixpkgs pull requests](https://github.com/NixOS/nixpkgs/pulls)

**Notify maintainers**
@fufexan 

-----

Note for maintainers: Please tag this issue in your PR.
Thanks for your work!
---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by kaytwastaken** [comment]
Seconding this as when I try to rebuild it fails due to a 404 on https://github.com/ppy/osu/releases/download/2024.517.0/osu.AppImage

**Comment by Luk45135** [comment]
Fixed with latest commit ddf67a243c20d781563d6a4066be164720b32afa
