### ISSUE TITLE
Broken launcher from .desktop file

### ISSUE THREAD

**Issue by damccull** [fufexan/nix-gaming#206]
After the update to RSI launcher 2.0, I'm getting this error when clicking on the 'Applications' icon for star citizen.

![image](https://github.com/user-attachments/assets/ea1e9626-bd78-4cc1-8097-6abbeda13a42)

The desktop file is
```ini
# /home/damccull/.local/share/applications/wine/Programs/Roberts Space Industries/RSI\ Launcher.desktop

[Desktop Entry]
Name=RSI Launcher
Exec=env WINEPREFIX="/home/damccull/Games/star-citizen" wine C:\\\\ProgramData\\\\Microsoft\\\\Windows\\\\Start\\ Menu\\\\Programs\\\\Roberts\\ Space\\ Industries\\\\RSI\\ Launcher.lnk
Type=Application
StartupNotify=true
Comment=RSI Launcher
Path=/home/damccull/Games/star-citizen/dosdevices/c:/Program Files/Roberts Space Industries/RSI Launcher
Icon=341A_RSI Launcher.0
StartupWMClass=rsi launcher.exe

```

However, when I run it from the terminal with the command 'star-citizen', it launches just fine. How do I solve this?

**Comment by fufexan** [comment]
@LovingMelody

**Comment by LovingMelody** [comment]
Use the included icon from the package. It should be listed as "Star Citizen" I'll have to disable the auto icon generation.

**Comment by damccull** [comment]
OK! New info. That previously listed .desktop file was likely generated by bottles when I was doing some experiments. I have found this one:
```
[Desktop Entry]
Categories=Game
Comment=Star Citizen - Alpha
Exec=/nix/store/jim42dmqndxw7g7c38bngwzini3nmj45-star-citizen/bin/star-citizen %U
Icon=/nix/store/sdxh3gdwx50z279xrmbiy9w76s6yd5dd-255031314-2fac3a8d-a927-4aa9-a9ad-1c3e14466c20.png
MimeType=application/x-star-citizen-launcher
Name=Star Citizen
Type=Application
Version=1.4
```
located at `/etc/profiles/per-user/damccull/share/applications`.

This file is still causing that same error screen I pasted above, but typing `star-citizen` into the cli still works fine. What is the difference here?
