### ISSUE TITLE
feature: add wine-ge as a package

### ISSUE THREAD

**Issue by imsofi** [fufexan/nix-gaming#28]
Pretty simple, glorious eggroll has their own wine package similar to tk-glitch.

Wine-GE seems easier to package as it follows the patch-set for proton-ge and does not ship with a customizable toggle-set like Wine-TkG. 

It may be a nicer default as a "works for most games" style wine.

Link to repo: https://github.com/GloriousEggroll/wine-ge-custom

**Comment by fufexan** [comment]
Thanks for the suggestion! I've thought about adding it but never got to do it. Will search for some time to package it.

**Comment by fufexan** [comment]
Does wine-ge have a patched source like [wine-tkg](https://github.com/Tk-Glitch/wine-tkg) does? It would make building easier as I could just integrate it into what I already have set up.

**Comment by imsofi** [comment]
While im not 100% sure, this seems to be a patched wine repo using the `ProtonX-XX` like tags.

https://github.com/GloriousEggroll/proton-wine/commits/Proton7-20

**Comment by fufexan** [comment]
Okay I've added it [here](https://github.com/fufexan/nix-gaming/tree/wine-ge). If it builds fine and works as expected, I'll merge it into main.

**Comment by fufexan** [comment]
Okay, it built and is now in master. Can you check whether it works as it should @imsofi?

**Comment by imsofi** [comment]
I do not have access to my NixOS machine at the moment, but testing this wine-ge package on my Fedora machine, it does work as it should with `notepad.exe` and has the correct  the extra set of patches inside of `winecfg` from the `-ge` branch.

Great work! :D
