### ISSUE TITLE
Need example

### ISSUE THREAD

**Issue by Nosirus** [fufexan/nix-gaming#34]
I'm trying to install Warframe in the most efficient way, without using steam

But I need an example, the only one I could find is this one.
https://www.reddit.com/r/NixOS/comments/sflmgj/wine_issue/

My home is not permanent, that's why being able to move it would suit me

any help would be appreciated, i still have a bit of trouble with some aspect of nix

**Comment by fufexan** [comment]
Please elaborate more on what the issue is.

> But I need an example, the only one I could find is this one.

That example is for osu! and it's from this repo. Not sure how it's relevant.

> My home is not permanent, that's why being able to move it would suit me

That should be something you take care of. In case of impermanence, you can add paths that won't be deleted on boot.
