### ISSUE TITLE
[Request] GitHub Actions to update packages

### ISSUE THREAD

**Issue by SuperSamus** [fufexan/nix-gaming#41]
`wine-tkg` and `wine-ge` are frequently updated, and I think that having them be automatically updated here to the latest version via GitHub Actions would be nice to have.

Unfortunately, I have zero experience with GitHub Actions.

(Also, `flakes.lock` needs to be updated too, since `vkd3d` and `gecko` are fetched from nixpkgs. For that, think that [this](https://github.com/marketplace/actions/update-flake-lock) can be used?)

**Comment by SuperSamus** [comment]
Found a PR from nixpkgs that maybe could help: `https://github.com/NixOS/nixpkgs/pull/201917`.

**Comment by fufexan** [comment]
This may be easier to implement with something like npins or nvfetcher. I'll look into it.

**Comment by SuperSamus** [comment]
There still isn't one.
(I'm not adding it myself because I don't know if you'd like it updated along with the other packages or more rarely (e.g. weekly).

One of the reasons why updating it is useful is, for instance, SDL: the current flake.lock is using an old version that has problems with Nintendo Switch controllers, which have been fixed with newer versions.

**Comment by fufexan** [comment]
Oops, forgot about this. I'll add a weekly action for it.

**Comment by fufexan** [comment]
Added in e60190e.
