### ISSUE TITLE
`wine-ge`: OpenGL apps don't work

### ISSUE THREAD

**Issue by SuperSamus** [fufexan/nix-gaming#47]
When trying to open an OpenGL application with `wine-ge` (or a Direct3D application with WineD3D (that is, without DXVK)):
```
0024:err:wgl:X11DRV_WineGL_InitOpenglInfo  couldn't initialize OpenGL, expect problems
```
And the application crashes.

This doesn't happen with Wine devel from nixpkgs.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.9-zen1, NixOS, 23.05 (Stoat), 23.05.20230205.d25de66`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixos"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

EDIT: Still an issue as of February 17.

```console
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.12-zen1, NixOS, 23.05 (Stoat), 23.05.20230216.8c66bd1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by fufexan** [comment]
Well that's weird. Do you have `hardware.opengl.enable = true;` in your config?

**Comment by SuperSamus** [comment]
Yes. As I said, regular Wine doesn't have this issue.
(Also, #48 doesn't fix it, I tried it for this reason.)

**Comment by fufexan** [comment]
Maybe there has been an update to the wine-related files in nixpkgs that we don't have yet. I'll have to check.

**Comment by fufexan** [comment]
I just tried launching Cult of the Lamb with both `-ge` and `-tkg`. `-ge` gave me many errors and this window:
![image](https://user-images.githubusercontent.com/36706276/217109537-9130902c-5f62-41ad-b314-b9448544b22b.png)

`-tkg` launched the game, but it didn't get past the splash screen (possibly due to mismatching wine versions in the prefix).

I'll investigate further.

**Comment by SuperSamus** [comment]
(By the way, Wine-GE-Proton7-37 just released)

**Comment by fufexan** [comment]
I've updated `wine-ge` to `Proton7-37`, along with nixpkgs update and removal of `openal` and `vkd3d`, from your PR.

I've tried running Cult of the Lamb again from within a clean prefix, with `dxvk` installed, and it worked perfectly.

If this still isn't enough to make wine work for you I'm out of ideas.

**Comment by SuperSamus** [comment]
With DXVK it runs with Vulkan, not OpenGL. Try *without* DXVK.
I know, that there is rarely any reason to not use DXVK, but some games use directly OpenGL (e.g. Into The Breach), and in that case Vulkan isn't used.
(Try [OpenGLChecker](https://sourceforge.net/projects/openglchecker/files/Release/1.2/OpenGLChecker_1.2_win32.zip/download).)

(Anyway, still no dice after a `nix flake update`+`nixos-rebuild`.)

**Comment by fufexan** [comment]
Without `dxvk` it gives the error in the screenshot I posted earlier, even after the update. Not sure what's causing it.

**Comment by SuperSamus** [comment]
So, I found out that `LD_LIBRARY_PATH="/run/opengl-driver/lib:/run/opengl-driver-32/lib"` fixes the problem.
Any idea why?

**Comment by fufexan** [comment]
Not really. I assume you have `hardware.opengl.driSupport32Bit` set to true? (Check through the repl, as I don't have it directly enabled in my config but it still is enabled and works).

**Comment by SuperSamus** [comment]
Yes, I have.

**Comment by SuperSamus** [comment]
By the way, the issue doesn't manifest in FHS environments.

Anyway, on nixpkgs, staging was recently merged, maybe it fixes something?
Otherwise, I guess that the best course of action would be to workaround the issue with something like [`addOpenGLRunpath`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/add-opengl-runpath/) (both 32 bit and 64 bit).
(And add comments suggesting that you try removing the workaround from time to time to see if it magically fixes the problem).

**Comment by SuperSamus** [comment]
Nope, updating `flake.lock` did nothing.
