### ISSUE TITLE
Shebang in winecfg from wine-ge isn't patched

### ISSUE THREAD

**Issue by kurnevsky** [fufexan/nix-gaming#51]
winecfg from wine-ge doesn't work because it contains /bin/sh shebang. I'm not sure why - I don't see how it's patched in wine from nixpkgs.

**Comment by fufexan** [comment]
![image](https://user-images.githubusercontent.com/36706276/219866368-67e0ea81-266d-4635-b6ca-5b8723f8ac83.png)
It does work for me.

The use of `/bin/sh` should not affect anything, since NixOS has that path available, along with `/usr/bin/env`.

**Comment by kurnevsky** [comment]
Oh, I messed it up with my sandboxing config. I noticed this difference between wine from nixpgks and wine-ge and thought it was the problem. Sorry for the noise.
