### ISSUE TITLE
[Game Request] tModLoader

### ISSUE THREAD

**Issue by NotAShelf** [fufexan/nix-gaming#64]
tModLoader is an extensive modding API for Terraria, providing both a modding client and a server client in the same package.

This is more of a TODO and a discussion issue than a "request", as I intend to get to it myself soon.

Q: Would we be able to be able to use home-manager options to
     1. auto-start server on launch, this should be as simple as providing a systemd service hooked to a hm option
     2. provide options such as port or player count in the home-manager module, which translate to flags appeneded to the server start script
     3. optionally wrap the player client with steam-run and `SDL_VIDEODRIVER=x11`

**Comment by fufexan** [comment]
Why have it be a HM module? I think having it as a NixOS module would be better, since people who run servers usually don't have HM installed there.

**Comment by NotAShelf** [comment]
In that case we probably should separate the modules. I don't think a game client belongs to nixos modules.

**Comment by NotAShelf** [comment]
> Any updates on this, @NotAShelf?

At the moment, no.
I was not able to figure out a proper way to handle configuration file (for both client and server) last time and postponed the project due to my sheer lack of free time. I might return to this next week.

**Comment by GetPsyched** [comment]
All right!
