### ISSUE TITLE
osu-lazer-bin won't build

### ISSUE THREAD

**Issue by sleroq** [fufexan/nix-gaming#70]
Pinned version (2023.510.0) seems to be absent on Github which is causing the [update.sh](https://github.com/fufexan/nix-gaming/blob/c93a108f93c4ee68e175d889a763e3b4a7453264/pkgs/osu-lazer-bin/update.sh) script to not work either.

**Comment by fufexan** [comment]
It was probably deleted in favor of 2023.511.0. Will update.

**Comment by fufexan** [comment]
It is now pushed. Can you check whether it works?

**Comment by sleroq** [comment]
It works! Thank you for taking the time to solve this issue.
