### ISSUE TITLE
Allow unfree packages in flake?

### ISSUE THREAD

**Issue by fufexan** [fufexan/nix-gaming#9]
The current mechanism doesn't include that, but we do provide packages with unfree licenses, such as `osu-lazer-bin`, and maybe others in the future. 

Should we enable `allowUnfree` in this flake, and implicitly in users' flake configs? Or should we leave it as is, requiring users to add
`NIXPKGS_ALLOW_UNFREE=1 nixos-rebuild ... --impure` when building?

**Comment by MagicRB** [comment]
No you should make it configurable IMO, definitely not allow by default. By default IMO `osu-lazer-bin` should be disabled too, it should be opt in with a fat warning.

**Comment by fufexan** [comment]
Sure! Any idea how I could make something like that (using something like `nix-gaming.allowUnfree`, like the nixpkgs mechanism)?

**Comment by MagicRB** [comment]
I'll take a look at the code.

**Comment by fufexan** [comment]
Take a look at the [rewritten flake](https://github.com/fufexan/nix-gaming/tree/testing) branch for a `utils`-free flake that may make implementing this easier.

**Comment by fufexan** [comment]
Following the decision that only `packages` would be affected by the change, I'll enable unfree packages.
