### ISSUE TITLE
Proton-GE doesn't specify dependencies

### ISSUE THREAD

**Issue by zyrain** [fufexan/nix-gaming#92]
Just got Proton GE working, but I had to manually add python3 and wineWowPackages to my system packages manually to get it to work.   I believe the right thing to do is add them to the build inputs in the derivation, e.g.

 buildInputs = [
    python3
    wineWowPackages.stable
  ];

**Comment by NotAShelf** [comment]
Neither of those packages are listed as dependencies by proton-ge, and nor do I have them (at least python) in my system packages.

I don't think this is a necessary change, but I'll go ahead and test it soon:tm:

**Comment by NotAShelf** [comment]
P.S.
we actually don't "build" anything, so having those packages in buildInputs doesn't look like they'll change anything.

See here: https://github.com/GloriousEggroll/proton-ge-custom#manual

**Comment by zyrain** [comment]
Ah, yes, it would be runtime inputs.

**Comment by chayleaf** [comment]
Proton is supposed to be used by Steam. Running it outside of Steam isn't supported.

**Comment by fufexan** [comment]
I guess this is solved. Closing.
