### ISSUE TITLE
npins proton-wine pointing to wrong release

### ISSUE THREAD

**Issue by LovingMelody** [fufexan/nix-gaming#94]
Current wine npins targets a[ game specific release](https://github.com/fufexan/nix-gaming/blob/21d50ed37b0dba1a8b2223a4433aaaa16ff5137c/npins/sources.json#L108).

**Comment by fufexan** [comment]
Fixed in https://github.com/fufexan/nix-gaming/commit/24e7c105bb9c781bb508cf78f721e5f43b34f74b.

**Comment by LovingMelody** [comment]
broken again in [9bb4b83](https://github.com/fufexan/nix-gaming/commit/9bb4b83)

**Comment by fufexan** [comment]
I can make it not use npins, but then someone will have to manually update it.
