### ISSUE TITLE
wine-discord-ipc-bridge on steam games

### ISSUE THREAD

**Issue by 2Epik4u** [fufexan/nix-gaming#96]
in wine discord ipc bridge repository (https://github.com/0e4ef622/wine-discord-ipc-bridge/) there is a shell script that allows it to work on proton. however I haven't had any luck using it on nixos. is there any way to get the bridge working on steam games?

**Comment by 2Epik4u** [comment]
got it to work properly, all you need to do is set the bridge path to where winediscordipcbridge.exe is. and by default it checks in the same directory. I think you can just paste the script in the same directory and it will work.

**Comment by fufexan** [comment]
In that case we could include the script in `wine-discord-ipc-bridge/bin`.
