### ISSUE TITLE
Cachix seems to be inconsistent

### ISSUE THREAD

**Issue by SuperSamus** [fufexan/nix-gaming#97]
Right now, if I try to install `wine-ge`, Nix will compile it instead of grabbing it from [Cachix](https://app.cachix.org/cache/nix-gaming).
This is despite the latest version being released 3 days ago, shouldn't it have already been built by this point?
It's not the first time it happens, and I fear this will not be the last.
(Also, `wine-tkg` is grabbed just fine, so I don't know...)

**Comment by fufexan** [comment]
Looks like Proton8-13 isn't in the cache, but Proton8-12 is (the one from c214fc2). I'll check the logs to see what happened.

**Comment by fufexan** [comment]
Ok the issue was that the build workflow does not run after the bot pushes changes. I'll fix that soon.

**Comment by SuperSamus** [comment]
Actions seem to be acting up again. https://github.com/fufexan/nix-gaming/actions/runs/7256005497/
> FailFast: cancelling since parallel instance has failed

(`wine-ge` compiled with no issues on my machine)

**Comment by fufexan** [comment]
It's not acting up, `faf-client` is broken (again). We're waiting on @chayleaf to fix it.
